name: release

on:
  push:
    tags: ['v*.*.*']

permissions:
  contents: read
  id-token: write
  attestations: write

jobs:
  build:
    uses: cash-track/.github/.github/workflows/build.yml@main
    with:
      image: cashtrack/website
    secrets: inherit
  deploy:
    needs: build
    uses: cash-track/.github/.github/workflows/deploy.yml@main
    with:
      service: website
    secrets: inherit
